create table if not exists correspondant_data_dates(
id integer not null,
owner_brl varchar(255) null,
brl_effective_date varchar(255) null,
brl_expired char null,
brl_sourced_date varchar(255) null,
brl_exposed_date varchar(255) null,
brl_published_date varchar(255) null,
brl_consumed_date varchar(255) null,
go_live_date varchar(255) null,
oat_completion_date  varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint correspondant_data_dates_pk primary key(id));